### PR TITLE
Update default config file

### PR DESCRIPTION
**Pull request by TheBearodactyl**

### CODE REVIEW

**Comment by blyxyas** [comment]
I mean, the project is dead...
LGTM, thanks! :heart:

**Comment by TheBearodactyl** [comment]
> I mean, the project is dead... LGTM, thanks! ❤️

i just found it a few days ago, why is it already dead :sob:

**Comment by blyxyas** [comment]
It has been dead for a few months TwT, it wasn't really anything at the time, cuz I didn't really have all that time.

If you'd like to maintain it, it's available

**Comment by TheBearodactyl** [comment]
> It has been dead for a few months TwT, it wasn't really anything at the time, cuz I didn't really have all that time.
> 
> If you'd like to maintain it, it's available

probably will, this tool is incredibly useful for people like me who can write amazing markdown but not so great html :3

**Comment by TheBearodactyl** [comment]
@blyxyas could you add me as an owner on crates.io real quick?

**Comment by blyxyas** [comment]
Hmmm I invited you, don't kidnap the project, that would be silly :3

**Comment by TheBearodactyl** [comment]
> Hmmm I invited you, don't kidnap the project, that would be silly :3

i won't kidnap it lol, also thanks :D

**Pull request merged**
